### ISSUE TITLE
是否有联系方式，我发了邮件给你，我这边一直环境搭建不成功！

### ISSUE THREAD

**Issue by Zosimer** [pengcao/chinese_ocr#2]

**Comment by pengcao** [comment]
你是在什么环境搭建的？  后面我在虚拟机上搭建，然后你去下载吧，估计这周末发出来吧。

**Comment by pengcao** [comment]
你可以把，你搭建过程中出现的错误贴出来么？  我看看。

**Comment by pengcao** [comment]
不好意思   之前说的虚拟机压缩完有8个多G上传不到百度云盘上。你可以把你遇到的问题发给我。
